[package]
name = "helpers"
version = "0.1.0"
authors = ["placinta@gmail.com"]
edition = "2021"

[dependencies]
color-eyre = "0.5.10"
thiserror = "1.0.22"
itertools = "0"
derive_more = "0.99.17"
tailsome = "0.1.0"
enum-iterator = "1.2.0"
num_enum = "0.5.7"
